-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
# SELECT I.DATETIME "I.DATETIME", O.DATETIME "O.DATETIME", O.NAME
  FROM ANIMAL_INS I
 RIGHT JOIN ANIMAL_OUTS O
 USING (ANIMAL_ID)
 WHERE I.DATETIME IS NULL
   AND O.DATETIME IS NOT NULL
 ORDER BY I.ANIMAL_ID
 